#!/usr/bin/env bash

set -euo pipefail

extract_tarball() {
  rm -rf node
  mkdir node
  tar -xf "tarball_path/pnpm_v${version}_linux_x64_bionic_"*".tgz" -C node
}

check_version() {
  actual_version="$(./node/bin/node --version)"
  if [[ "${actual_version}" != "v${version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${version}"
    exit 1
  fi
}

main() {
  local version
  version=

  while test $# -gt 0; do
    case $1 in
      --version)
        version=$2
        shift
        ;;
      *)
        echo >&2 "Invalid argument: $1"
        exit 1
        ;;
    esac
    shift
  done

  if [[ "${version}" == "" ]]; then
    echo "Version is required"
    exit 1
  fi

  extract_tarball
  check_version

  echo "All Node bionic dependency tests passed!"
}

main "${@:-}"