#!/usr/bin/env bash

set -euo pipefail

extract_tarball() {
  rm -rf pnpm
  mkdir pnpm
  tar -xf "tarball_path/pnpm_${version}_${os}_${arch}_bionic_"*".tgz" -C pnpm
}

check_version() {
  actual_version="$(./pnpm/bin/pnpm --version)"
  if [[ "${actual_version}" != "${version}" ]]; then
    echo "Version ${actual_version} does not match expected version ${version}"
    exit 1
  fi
}

main() {
  local version os arch
  version=

  # default values
  os="linux"
  arch="x64"

  while test $# -gt 0; do
    case $1 in
      --version)
        version=$2
        shift
        ;;
      -os)
        os="${2}"
        shift 2
        ;;

      --arch)
        arch="${2}"
        shift 2
        ;;
      *)
        echo >&2 "Invalid argument: $1"
        exit 1
        ;;
    esac
    shift
  done

  if [[ "${version}" == "" ]]; then
    echo "Version is required"
    exit 1
  fi

  extract_tarball
  check_version

  echo "All Node bionic dependency tests passed!"
}

main "${@:-}"